### ISSUE TITLE
事项编号字段定义

### ISSUE THREAD

**Issue by Guo-Zhang** [quanttide/quanttide-specification-of-project-management#6]
# 编号方式

对于事项的编号方式，可以根据具体的业务需求和使用场景来决定。

统一编号：如果你希望对所有事项进行统一编号，可以为每个事项分配一个唯一的编号，不考虑事项的类型。这种方式简化了编号规则，方便了事项的排序和查找。每个新创建的事项都会自动分配一个递增的编号，不论是史诗、用户故事还是任务。

分别编号：如果你希望根据事项的类型进行分别编号，可以为不同类型的事项设计不同的编号规则。例如，对于史诗、用户故事和任务分别使用不同的编号前缀或编号规则。这种方式可以更好地区分不同类型的事项，并在编号中体现出事项的层次结构。

选择哪种方式取决于你的项目需求和团队的偏好。如果你的项目中事项的类型相对较少且简单，统一编号可能更加简洁和易于管理。如果事项类型较多且需要明确的层级结构，分别编号可以提供更多的灵活性和可读性。

无论选择哪种方式，你可以在`Matter`类中添加一个辅助方法来生成编号，可以是静态方法或实例方法，根据需要自定义编号规则，并确保生成的编号在创建事项时被正确地分配。

## 分别编号

如果选择分别编号的方式，以下是一些具体的建议：

1. 制定编号规则：定义每种事项类型的编号规则，包括前缀、数字格式和递增规则等。例如，可以使用"E"作为史诗的前缀，"U"作为用户故事的前缀，"T"作为任务的前缀。

2. 层级编号：如果事项存在层级结构，可以考虑在编号中体现层级关系。例如，可以为史诗编号为"E1"、"E2"等，为用户故事编号为"U1"、"U2"等，以此类推。这样可以在编号中直观地反映出事项的层次关系。

3. 自动编号生成：为了方便管理和维护，可以考虑在系统中实现自动编号生成的功能。当创建新的事项时，根据事项的类型自动生成相应的编号。这样可以减少人工操作，提高系统的易用性和准确性。

4. 编号展示和搜索：在用户界面中展示事项的编号，并为用户提供根据编号进行搜索和筛选的功能。这样用户可以通过编号快速定位和识别特定的事项。

5. 编号的唯一性：确保每个事项的编号在系统中是唯一的，避免重复和混淆。可以在系统中添加验证机制，检查新创建的事项的编号是否与已有的编号冲突。

6. 文档和培训：在团队内部进行文档和培训，明确事项编号的规则和使用方式，以便团队成员能够正确理解和应用编号。

这些建议可以帮助你在选择分别编号的方式时制定规则和实施方案。根据你的具体项目需求，你可以根据这些建议进行定制和调整。如果你需要更多的指导或有其他问题，请随时告诉我。

### 类型转换的编号方案

当将一般事项转换为特殊事项类型时，为该特殊事项类型生成一个新的唯一编号，避免与已有的特殊事项类型的编号冲突。
当将特殊事项类型转换为一般事项时，可以保留原有的编号，或者为其生成一个新的唯一编号，避免与已有的一般事项的编号冲突。

**Comment by Guo-Zhang** [comment]
# 服务端实现

设计 `number` 字段为多态模型内统一编号还是根据类型分别编号，取决于你的业务需求和具体场景。下面我将介绍两种方案的优缺点，以帮助你做出决策：

1. 统一编号（多态模型内编号）：
   - 优点：
     - 统一编号可以简化数据管理和查询，所有类型的事项都使用同一个编号字段，减少了字段的冗余和复杂性。
     - 统一编号使得事项之间的排序和比较更加直观和方便。
   - 缺点：
     - 统一编号可能导致编号的不连续性，因为不同类型的事项可能在编号序列中交叉出现。
     - 统一编号可能会给查询和过滤带来额外的复杂性，因为你需要根据编号和类型进行筛选和排序。

2. 分别编号（根据类型分别编号）：
   - 优点：
     - 分别编号可以确保每个类型的事项都有独立的编号序列，编号的连续性更高。
     - 分别编号可以简化查询和过滤，因为你可以直接通过编号和类型进行筛选和排序。
   - 缺点：
     - 分别编号增加了字段的冗余和复杂性，每个类型的事项都需要维护自己的编号字段。
     - 分别编号可能导致不同类型的事项在编号上存在重叠，需要额外的逻辑来确保编号的唯一性。

综上所述，如果你更看重编号的连续性和类型独立性，以及对查询和过滤的简化，可以选择分别编号的方案。如果你更看重数据的简洁性和统一性，以及对事项之间排序和比较的方便性，可以选择统一编号的方案。

**Comment by Guo-Zhang** [comment]
# Jira实现方案

Jira 的任务编号规则是可以根据用户需求和配置进行自定义的。默认情况下，Jira 使用了一种常见的任务编号规则，通常是由项目键和数字序列组成的。

下面是 Jira 默认的任务编号规则示例：

```
<项目键>-<数字序列>
```

其中：
- `<项目键>` 是项目的唯一标识符，通常是项目名称或缩写的大写形式。
- `<数字序列>` 是一个递增的数字，用于唯一标识每个任务。它可以是任意长度的数字，通常是从 1 开始的连续序列。

例如，假设有一个名为 "PROJECT" 的项目，那么它的任务编号可能如下：

```
PROJECT-1
PROJECT-2
PROJECT-3
```

这是 Jira 默认的任务编号规则，但你可以根据需要进行自定义。Jira 提供了灵活的自定义功能，允许你定义自己的任务编号格式，并可以包含项目键、日期、自定义字段等。你可以根据以下步骤在 Jira 中自定义任务编号规则：

1. 登录到 Jira 并进入你的项目。
2. 点击项目设置（Project Settings）。
3. 在左侧菜单中，找到并点击 "任务"（Issue）。
4. 在 "序列"（Sequences）部分，你可以选择一个预定义的序列或创建自己的序列。
5. 如果你选择创建自己的序列，你可以定义一个模板，包括项目键、日期、自定义字段等，并可以指定开始值、步长等。

通过自定义任务编号规则，你可以根据你的项目需求和组织约定，制定适合自己团队的任务编号方案。

需要注意的是，Jira 的任务编号规则是在项目级别进行配置的，因此每个项目可以有自己的编号规则。这使得不同项目可以采用不同的编号方案。

# 我们的改进

对于你提出的事项领域模型的编号问题，我可以给出一些建议供参考。

基于你的设计理念，希望在租户层面统一编号，而不是项目层面。这意味着你希望在整个租户范围内为事项进行编号，而不仅仅局限于单个项目。

以下是一种可能的方案：

1. 定义租户：首先，你需要在你的项目管理软件中定义租户的概念。租户可以是组织、团队或其他可以共享编号的实体。

2. 设计编号规则：根据你的需求，设计一个编号规则，该规则可以在租户级别唯一标识事项。这可以是一个有意义的标识符，例如使用租户名称的缩写或其他标识符，结合一个递增的数字序列。

3. 统一编号生成：在你的软件中，实现一个机制来生成和管理统一的编号。这可以是一个独立的服务或模块，负责为新创建的事项分配编号，并确保在租户范围内的唯一性。你可以根据编号规则和租户标识符来生成编号。

4. 编号的展示和使用：确保在你的软件界面中展示事项的编号。可以在事项的详细信息页面、列表视图和报表中显示编号。此外，你还可以提供搜索、过滤和排序功能，以便用户根据编号进行操作。

需要注意的是，这只是一种基本的方案示例。你可以根据你的具体需求进行调整和扩展。确保你的编号方案满足租户层面的唯一性要求，并与你的软件的其他功能和模块协调一致。

最重要的是，在设计并实现编号方案之前，你应该仔细考虑你的业务需求、数据结构和用户体验。确保你的编号方案能够满足你的预期目标，并为用户提供良好的使用体验。

**Comment by Guo-Zhang** [comment]
@Guo-Zhang @AnnaPanChina 分别编号。

**Comment by Guo-Zhang** [comment]
系统内部目前的逻辑是最大编号+1

全局：Matter, DeletedMatter, others. 统一查询。
类型：Story, DeletedStory/DeletedMatter。

1. 标记is_deleted方案。缺点在于REST API的定义、可测试。
2. Deleted表。
3. 单独变量存。不需要了。

**Comment by Guo-Zhang** [comment]
@AnnaPanChina 认为数字应该可变、人控制。 
@Guo-Zhang 认为数字应该不可变。

**Comment by Guo-Zhang** [comment]
https://github.com/quanttide/django-quanttide/blob/886b1ab40d998b97dbdb0df495d98b0b4920d638/django_quanttide/models/fields.py#L50

https://github.com/quanttide/django-quanttide/blob/886b1ab40d998b97dbdb0df495d98b0b4920d638/tests/test_models_fields.py#L45

https://github.com/quanttide/django-quanttide/blob/main/tests/test_models_polymorphic.py

**Comment by Guo-Zhang** [comment]
从技术上考虑，全局编号比较简单且确定，不需要考虑各种意外情况。可以使用多态模型统一查询的方式获取最大数并自增。

关于编号膨胀的问题，可以加上年月日的方式解决，根据创建日期，每个新年份、新月份、新日期。Django支持设置unique_year/month/day的选项。

**Comment by Guo-Zhang** [comment]
出版社对出版物进行编号通常是为了在其内部进行管理和跟踪，并方便销售、分发和库存管理。出版物编号可以包括以下几个方面：

1.ISBN（国际标准书号）：ISBN是一种全球唯一的标识符，用于识别图书和其他出版物。它由13位数字组成，分为五个部分：前缀元素、注册组元素、出版社元素、标题元素和校验位。ISBN可以通过国家或地区的ISBN机构进行申请和分配。
2.ISSN（国际标准连续出版物号码）：ISSN是一种用于标识连续出版物（如期刊、杂志）的标识符。它由八位数字组成，通常以两个四位数和一个校验位的形式表示。ISSN由国际标准化组织（ISO）的ISSN国家中心分配。
3.版次号：对于同一出版物的不同版本或重印本，可以使用版次号进行区分。版次号是一个数字或字母组成的标识符，表示出版物的具体版本。例如，第一版可以标记为 "第1版" 或 "1st edition"。
4.编辑号：编辑号是出版社内部为了管理和跟踪出版物而分配的编号或代码。它可能是出版社自定义的一串数字、字母或符号的组合，用于区分不同的出版物。
5.出版物条码：出版社可以为每个出版物生成独特的条码，以便在销售和库存管理环节中进行扫描和识别。出版物条码通常基于国际商品编码（GTIN）标准，如通用产品代码（UPC）或国际文章编号（EAN）。

这些编号系统通常由国际组织或国家机构颁发和管理，以确保标识符的唯一性和全球范围的可识别性。
需要注意的是，不同出版社可能会根据其内部需求和流程在编号方面有所差异，因此具体的编号规则和流程可能会有所不同。

**Comment by AnnaPanChina** [comment]
@Guo-Zhang 我的想法是全局编号可以包含项目的编号作为前缀，比如有两个项目A和B，前者创建于2018年，后者创建于2019年，那么项目A本身的编号可以为2018P1，项目B为2019P2。
A项目有5个事项，那么不区分类型，就以2018P1-1、2018P1-2、2018P1-3、2018P1-4、2018P1-5作为编号。
B项目也有5个事项，就以2019P2-1、2019P2-2、2019P2-3、2019P2-4、2019P2-5作为编号。
A项目结束后，把全局编号里的2018P1开头的所有事项删除就可以了，在归档该项目的时候，如果有剩余的事项需要保存就以2018P1作为编号归档。

**Comment by Guo-Zhang** [comment]
决定：
1. 对一个租户内的所有事项全局编号。
2. 使用年份+编号的规则，如“2023年23号”事项，日常表述时可以省略当年年份。
